version: '3.9'

services:
  nopcommerce_database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: nopcommerce_mssql_server
    environment:
      SA_PASSWORD: "H@ppy000"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - nopcommerce_data:/var/opt/mssql

  nopcommerce_web:
    build: .
    container_name: nopcommerce
    ports:
      - "8080:80"
    depends_on:
      - nopcommerce_database
    environment:
      DB_HOST: nopcommerce_database
      ConnectionStrings__DefaultConnection: "Server=nopcommerce_database;Database=BambooCard;User ID=sa;Password=H@ppy000;"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:
  nopcommerce_data: